### ISSUE TITLE
Push upstream?

### ISSUE THREAD

**Issue by vincentbernat** [Fuco1/org-pretty-table#1]
Hey!

This minor mode works fine for me. Do you intend to push it upstream? Or have it somehow integrated as an option directly in Org?

**Comment by Fuco1** [comment]
Hm, I just tried it and it doesn't work for me anymore.  The way this is written is quite inefficient too, I think that it could be made much simpler if we allow ourselves to change code in org (which I wanted to avoid in order to make this stand-alone package).

I don't think I'll push this upstream, no.  If you want to hack on this, I can give you commit access or you can fork and pull request.

Also, my workflow changed a lot since back then, now I usually export the tables to html or something else and view it there, I interact minimally with org inside emacs (that is, "consuming"-wise)

**Comment by felideon** [comment]
Hmm, works for me on GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))

**Comment by amno1** [comment]
Still same opinion? Seems to work fine, at least for me in 28.0.50. 

I have written small package to auto display readme files (not published yet), and I am using this if installed to display prettier tables when in org-mode. Would be nice if it went upstream so more users have it installed.

**Comment by Fuco1** [comment]
If you want to push it upstream I don't oppose but I won't pursue that myself.  

I've signed the contributor papers for Emacs so there should be no legal problems.

**Comment by amno1** [comment]
Matus Goljer <notifications@github.com> writes:

> If you want to push it upstream I don't oppose but I won't pursue that myself.
>
> I've signed the contributor papers for Emacs so there should be no legal problems.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
I am probably not the right person to do that, but I can at least
suggest it for the inclusion.
